### ISSUE TITLE
Need a whitespace/padding between icon and title text

### ISSUE THREAD

**Issue by nikhilmandlik** [nasa/openmct#3601]
### Description:
Need a whitespace/padding between icon and title text

### Testing instructions:
1. open any preview window
1. observer there is no padding between icon and title text

### Screenshots:
![Screen Shot 2020-12-14 at 2 50 14 PM](https://user-images.githubusercontent.com/1292612/102145224-b6645580-3e1b-11eb-9793-b5d0a6e4a3a1.png)

**Comment by deeptailor** [comment]
I believe this was fixed by PR #3497

**Comment by charlesh88** [comment]
Testathon 01-07-21 verified NOT fixed; in fact, the icon is now completely missing. Reopening.

**Comment by nikhilmandlik** [comment]
Verified Fixed.
Found issue icon missng: https://github.com/nasa/openmct/issues/3628
