### ISSUE TITLE
'Save' on Edit Properties updates objects in persistence even if no properties have changed

### ISSUE THREAD

**Issue by ozyx** [nasa/openmct#5705]
#### Summary

Every time a user clicks 'Save' on the Edit Properties window of an object, that object is revised in persistence regardless of whether or not any properties have changed.

#### Expected vs Current Behavior

If no properties have changed, an object revision should not be persisted.

#### Steps to Reproduce

Using CouchDB persistence plugin with browser's Network tab open:

1. Create an object
2. "Edit Properties" of the object
3. Do not edit any properties and click "Save"
4. Observe that a PUT request has been made, the revision# of the object in persistence has updated, even though all other properties retain the same values.

#### Environment

```
Version: 2.0.8-SNAPSHOT
Build Date: Wed Aug 24 2022 09:07:03 GMT-0700 (Pacific Daylight Time)
Revision: 84c1526f5eb2031b925144d11054aff1ace1fded
Branch: master
```

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [x] Does this have an impact on Performance?

**Comment by shefalijoshi** [comment]
Probably fixed by #5717

**Comment by ozyx** [comment]
Not fixed. Testathon 10/27/22

Clicking "edit properties" and hitting "Save" without changing anything still generates a PUT request to couch

**Comment by khalidadil** [comment]
I'm seeing the same thing ^

**Comment by davetsay** [comment]
not fixed. seeing a put request to couch and a subsequent `openmct.objects.get` call shows the time is updated.
