### ISSUE TITLE
Element styling unusable in Stacked Plots and Flex Layouts

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#6693]
#### Summary
First surfaced during VIPER sims as the NIRVSS position tried to setup displays for their position. In short, 
1. Styling in Flex Layouts and Stacked Plots is seriously broken. 
2. The user cannot easily select the parent Stacked Plot after having selected one of its children. 

Putting this altogether in a single issue as the two views seem to share some common problems. 

### Flexible Layouts
1. Add several telemetry points to the layout, then select one and attempt to give it a style. The Style panel lets you think you can, but no style is applied:
![Screen Shot 2023-05-24 at 4 13 43 PM](https://github.com/nasa/openmct/assets/1056412/47a057b6-edcc-48e0-9fb3-4c8f1cf16fb4)

3. Select a container, in this example a column. Apply a style to that, and observe that only the _first_ element in that container is styled: 
![Screen Shot 2023-05-24 at 4 12 56 PM](https://github.com/nasa/openmct/assets/1056412/92a14856-7b27-4599-94f7-8eae9500d382)

4. Clicking another container in the layout will display the colors associated with the settings from step 2 above, even though another container has been selected. Changing the style here will affect the _first_ element in the _first_ container.
![Screen Shot 2023-05-24 at 4 13 57 PM](https://github.com/nasa/openmct/assets/1056412/a1dbc1ec-0008-4778-b31b-931ec99f29f6)

5. Saving, navving away and back will reveal that the entire Flex Layout has been styled: 
![Screen Shot 2023-05-24 at 4 18 34 PM](https://github.com/nasa/openmct/assets/1056412/c03cbfce-81e0-4c06-a114-3e73249e560c)

6. Coming back into Edit, and trying to style the whole Flex Layout ends up apparently styling the _first_ element, as in step 2 above; but wait...
![Screen Shot 2023-05-24 at 4 43 56 PM](https://github.com/nasa/openmct/assets/1056412/f06e2ed4-9c89-48ba-9f53-0369c535d983)

7. Saving, navving away and back will reveal (you guessed it) that the entire Flex Layout has been styled again, like 4.
8. WORST OF ALL, editing the layout and attempting to set the styles to "No Style" (particularly the text color) results in all text elements **being set to a color that's completely unreadable**:
![Screen Shot 2023-05-24 at 5 15 16 PM](https://github.com/nasa/openmct/assets/1056412/ca736885-dd14-4058-8897-f372476402da)
![Screen Shot 2023-05-24 at 5 20 40 PM](https://github.com/nasa/openmct/assets/1056412/4bf1820f-f005-4455-afd8-3dcc4a32a901)

It is now _impossible_ to reset the styling; the user can't even hard-code a different color onto the Flex Layout elements. At this point, the whole view is trashed.

### Stacked Plots
1. Add several telemetry points to the plot, but don't select one of them in the plot area. Attempt to apply a style to the whole domain object; observe the same problem as in Flex Layout step 5 above.
![Screen Shot 2023-05-24 at 4 27 48 PM](https://github.com/nasa/openmct/assets/1056412/0399ee67-caca-42f9-987c-67327780167b)

2. Select the child plot that appears to be styled. Note that the Styles tab indicates no style is applied:
![Screen Shot 2023-05-24 at 4 28 38 PM](https://github.com/nasa/openmct/assets/1056412/6258820d-a0ee-492a-9258-fed5d2893c84)

3. Select an unstyled child plot in the plot area and attempt to give it a style. The Style panel lets you think you can, but no style is applied; this is the same problem as seen in Flex Layouts step 1:
![Screen Shot 2023-05-24 at 4 28 54 PM](https://github.com/nasa/openmct/assets/1056412/6839643a-b3c2-4094-8f1b-2bbc37e1dcbd)

4. Saving, navving away and back will reveal that (unlike the Flex Layout) _no_ styles have been applied anywhere: 
![Screen Shot 2023-05-24 at 4 33 52 PM](https://github.com/nasa/openmct/assets/1056412/140718e9-8f50-46cd-8613-2a5fba9393bc)

5. Coming back into Edit reveals that the the Styles tab has retained the style that was "applied" even though no styling is visible:
![Screen Shot 2023-05-24 at 5 05 20 PM](https://github.com/nasa/openmct/assets/1056412/b6fccbc9-7b9d-483d-be56-a7c05249cc2a)

6. When editing and having selected a child plot element, the user cannot click anywhere to select the parent again. The only way to do it is to carefully click on a plot legend name. 

#### Expected vs Current Behavior

1. The Styles tab MUST recognize if an element can be styled or not. If it can't, it must have a disabled or other state that includes a message like "This element cannot be styled".
2. The overall Flex Layout or Stacked Plot itself MUST be style-able.
3. Individual child elements of Flex Layouts and Stacked Plots (telem points, child Overlay Plots, etc.) MUST BE STYLE-ABLE. If an overall style has been applied to the parent layout or plot, the individual styling should be able to coexist with that.
4. Flex Layout containers should NOT be style-able.
5. When the user chooses the "no style" option, REMOVE THE STYLE TAG - do not add a style attribute with a hard-coded color.
6. Conditional Styling MUST work everywhere that static styling does in the same way it does elsewhere.
7. Users MUST be able to click on the empty area above the plot and legend areas to select the parent Stacked Plot container.

#### Steps to Reproduce

See above.

#### Environment

* Open MCT Version:  2.2.0 
* Deployment Type:  VIPER MMOC
* OS: all
* Browser: all

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [X] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [X] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by akhenry** [comment]
Scope discussion 09/18
* Let's go after Stacked Plots first
* Treat Flex layouts as a regression
* Potentially related: sub-object editing in display layouts appears to also be broken (scope as separate issue)

**Comment by khalidadil** [comment]
This requirement was not addressed in this bugfix:
* Users MUST be able to click on the empty area above the plot and legend areas to select the parent Stacked Plot container. (also applies to Flexible Layouts)

After discussion with @charlesh88 it was broken into its own ticket that needs design discussion to make sure it's consistent across objects:
https://github.com/nasa/openmct/issues/7229

**Comment by charlesh88** [comment]
Testathon 2024-01-23 verified fixed. 
Note that there is still an issue where immutable domain objects (like telemetry end points) in both views cannot be styled - but that's another issue.
