### ISSUE TITLE
New items don't show up in the tree unless you expand/collapse the parent

### ISSUE THREAD

**Issue by shefalijoshi** [nasa/openmct#6838]
#### Summary
New items don't show up in the tree unless you expand/collapse the parent

#### Expected vs Current Behavior
Newly created items should show up in the tree as soon as it's been saved.

#### Steps to Reproduce
Using the Add Folder action, create a new folder (or item) in some location.
Observe that the tree does not show the newly added item unless you collapse and expand it

#### Environment

* Open MCT Version: 3.0.0
* Deployment Type: viper/testathon
* Browser: All
* OS: All

#### Impact Check List

- [x] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [x] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by ozyx** [comment]
Fixed by https://github.com/nasa/openmct/commit/6629454a489593383e1ea84bfd5e096ae079813f

This issue was caused due to items in the tree losing reactivity. Not modifying `this.treeItems` directly and wrapping tree-item creation in `reactive()` fixes the issue.

# Testing Instructions

- Follow the repro steps above and ensure that the folder appears in the tree correctly.
- Create various domain objects via the create menu in different levels of subfolders and ensure that they are created in the tree
- Use the "target" button and ensure that it scrolls to the item and expands all subfolders leading up to it

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 07/26/23

**Comment by rukmini-bose** [comment]
Not fixed 7/26/2023: I tried to create a Folder, and while it shows up in the Recent Objects, the tree does not update and the new Folder does not appear in the tree.

**Comment by charlesh88** [comment]
Testathon 2023-07-26: verified NOT fixed. Creating a Folder worked, but then creating an Overlay Plot afterward did not. Collapsing and expanding the containing folder does show the new object. Trying the same sequence again didn't exhibit any problems - this is sporadic.

**Comment by ozyx** [comment]
Found the cause.

When a scroll is performed on `mct-tree`, we call `updateVisibleItems()` which sets `this.visibleItems` to an array of whichever tree-items are in view. This controls what is rendered by Vue. When those components are unmounted, we unregister their composition listeners. However, those are never added back again so we lose composition listeners if we ever scroll a tree item out of view.

**Comment by rukmini-bose** [comment]
Verified Fixed Testathon 7/31/2023

**Comment by khalidadil** [comment]
Verified Fixed in Testathon on 07/31/23. Created 4 objects in a folder and had them consistently appear in the tree. Deleting all of the objects correctly removed them as well.

**Comment by charlesh88** [comment]
Verified fixed Testathon 2023-07-31.
