### ISSUE TITLE
[Time List view] Time List should not "auto-center"

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#7167]
**Is your feature request related to a problem? Please describe.**

When the Time List view is displaying a number of current events, it will continually try to vertically "auto-center" the display. This can have the result of hiding current events at the top of the list:

![Screen Shot 2023-10-18 at 9 59 49 AM](https://github.com/nasa/openmct/assets/1056412/5534a7fe-5468-4487-837d-f263e6225f5d)

**Describe the solution you'd like**
Change the "centering on now" approach to this algorithm: 
1. Show as many current and/or future events as possible, without scrolling any of either type beyond the top of the view area. 
2. _Only_ show past events if all other current and future events can be displayed.
3. If there are no past events in the current data set, then the centering algorithm could be turned off for efficiency.

![image](https://github.com/nasa/openmct/assets/1056412/c8acfac0-cd8d-4c12-92bc-8c44d7e3d840)

This would be at the expense of scrolling past items beyond the top of the view when necessary.

**Comment by shefalijoshi** [comment]
Testing instructions:
See above screenshots.
Current and Future activities should always be scrolled into view first
If there is room left over after displaying ALL current and future activities, then only a subset of past activities should be displayed.
If all activities are viewable in the current view then no auto scrolling should occur.
If there are no past activities, there should be no auto scrolling at all.

**Comment by shefalijoshi** [comment]
Should be fixed by https://github.com/nasa/openmct/pull/7194

**Comment by davetsay** [comment]
verified

**Comment by charlesh88** [comment]
Testathon 2024-01-31: verified NOT fixed. At some viewport heights, the compact Time List view will still auto-scroll in a way that hides a current Activity. Using the sim-9_025 plan:

#### Desired: Note current Activity at top in view:
![Screenshot 2024-01-31 at 2 49 08 PM](https://github.com/nasa/openmct/assets/1056412/9cbb238d-40e8-4b2c-9578-8baa41fac610)

#### Not desired: When auto-scrolled, top current Activity is now hidden:
![Screenshot 2024-01-31 at 2 49 15 PM](https://github.com/nasa/openmct/assets/1056412/e284aad2-5b99-4c79-b8b7-59d5b1484e43)

**Comment by unlikelyzero** [comment]
Won't fix and do https://github.com/nasa/openmct/issues/7449
