### ISSUE TITLE
[Table] Creating new objects in WARP results in javascript errors to the console

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#753]
There are two forms of this issue, which show two different error messages.

1. Creating a new object that goes immediately into edit mode throws the error below. To reproduce this, select a folder in the tree, and click on the create button to create a new Layout object. The error below will appear in the console.
```
angular.min.js:110 TypeError: Cannot read property 'getPath' of undefined
    at o (http://10.10.81.18:9080/static/main.js:14:9022)
    at r.value (http://10.10.81.18:9080/static/main.js:14:9406)
    at i.<anonymous> (http://10.10.81.18:9080/static/main.js:14:12489)
```
2. Creating a new object that goes to the properties dialog shows a different error in the console. To reproduce this, select a folder in the tree and click on the create button, and create a new Timer object. The error below will appear in the console.
```
Error when notifying listener: e.useCapability is not a function
    (anonymous function) @ angular.min.js:110
    (anonymous function) @ Topic.js:71
    notify @ Topic.js:67r @ MutationCapability.js:131
    o @ MutationCapability.js:150
    then.then @ MutationCapability.js:53
    n.mutate @ MutationCapability.js:159
    e.useCapability @ DomainObjectImpl.js:137
    e.persist @ PersistenceCapability.js:139
```

**Comment by VWoeltjen** [comment]
These look like they could be tree-related (from #739); I believe there are some unchecked uses of context there. The second stack trace is probably same root cause as #745 and should be resolved by #756

**Comment by VWoeltjen** [comment]
Want to diagnose and assess severity; do these impact what the user is seeing in the tree?

**Comment by VWoeltjen** [comment]
Verified that the second case is resolved by #756; will file PR for the first case shortly

**Comment by RCarvalhoNASA** [comment]
Testathon 20160317 these seem to be resolved

**Comment by charlesh88** [comment]
Newly created Timelines still throw console errors, but not the same as noted above.
